let youtubePlayer=null,youtubeReady=false,pendingSong=null;
const SONGS={first:{videoId:"VoEsEC2CLgE",startSeconds:121},final:{videoId:"ZWrhh8iMvhE",startSeconds:167}};
function onYouTubeIframeAPIReady(){youtubePlayer=new YT.Player("youtubePlayer",{width:"200",height:"200",playerVars:{playsinline:1,controls:0,rel:0,modestbranding:1},events:{onReady:()=>{youtubeReady=true;if(pendingSong==="first")playFirstSong();else if(pendingSong==="final")playFinalSong();}}});}
function loadSong(song){if(!youtubeReady||!youtubePlayer){pendingSong=song===SONGS.first?"first":"final";return;}pendingSong=null;youtubePlayer.loadVideoById({videoId:song.videoId,startSeconds:song.startSeconds});youtubePlayer.setVolume(75);}
function playFirstSong(){loadSong(SONGS.first)}function playFinalSong(){loadSong(SONGS.final)}
const startOverlay=document.getElementById("startOverlay"),startExperience=document.getElementById("startExperience");
startExperience?.addEventListener("click",()=>{playFirstSong();startOverlay?.classList.add("hide")});
const pages=document.querySelectorAll(".page"),nextBtn=document.getElementById("nextPage"),prevBtn=document.getElementById("prevPage");let currentPage=0;
function stopAllVideos(){document.querySelectorAll("video").forEach(v=>v.pause())}
function showPage(index){if(!pages.length)return;if(index<0)index=0;if(index>=pages.length)index=pages.length-1;stopAllVideos();pages.forEach(p=>p.classList.remove("active"));pages[index].classList.add("active");currentPage=index;if(prevBtn){prevBtn.disabled=currentPage===0;prevBtn.style.opacity=currentPage===0?".35":"1"}if(nextBtn){nextBtn.disabled=currentPage===pages.length-1;nextBtn.style.opacity=currentPage===pages.length-1?".35":"1"}}
nextBtn?.addEventListener("click",()=>showPage(currentPage+1));prevBtn?.addEventListener("click",()=>showPage(currentPage-1));showPage(0);
const birthDate=new Date("1998-07-13T00:00:00");
function updateAge(){const c=document.getElementById("ageCounter");if(!c)return;const now=new Date();let diff=Math.floor((now-birthDate)/1000);const years=Math.floor(diff/31557600);diff-=years*31557600;const days=Math.floor(diff/86400);diff-=days*86400;const hours=Math.floor(diff/3600);diff-=hours*3600;const minutes=Math.floor(diff/60);const seconds=diff-minutes*60;c.innerHTML=`<div class="age-box"><strong>${years}</strong><span>Years</span></div><div class="age-box"><strong>${days}</strong><span>Days</span></div><div class="age-box"><strong>${hours}</strong><span>Hours</span></div><div class="age-box"><strong>${minutes}</strong><span>Minutes</span></div><div class="age-box"><strong>${seconds}</strong><span>Seconds</span></div><div class="age-box"><strong>∞</strong><span>Love</span></div>`}
updateAge();setInterval(updateAge,1000);
const envelope=document.getElementById("envelope");envelope?.addEventListener("click",()=>envelope.classList.toggle("open"));
const blowBtn=document.getElementById("blowBtn");blowBtn?.addEventListener("click",()=>{const flame=document.getElementById("flame"),smoke=document.getElementById("smoke"),message=document.getElementById("birthdayMessage");playFinalSong();if(flame){flame.style.opacity="0";flame.style.transform="translateX(-50%) scale(.2)";flame.style.boxShadow="none"}smoke?.classList.add("show");message?.classList.add("show");blowBtn.style.display="none";releaseMagic()});
function releaseMagic(){for(let i=0;i<150;i++){setTimeout(()=>{const m=document.createElement("div");m.className="float-magic";m.textContent=Math.random()>.48?"✦":"🤍";m.style.left=Math.random()*100+"vw";m.style.fontSize=16+Math.random()*22+"px";m.style.animationDuration=5+Math.random()*5+"s";document.body.appendChild(m);setTimeout(()=>m.remove(),10000)},i*38)}}
const canvas=document.getElementById("magicCanvas");if(canvas){const ctx=canvas.getContext("2d");let particles=[];function resizeCanvas(){canvas.width=window.innerWidth;canvas.height=window.innerHeight}resizeCanvas();window.addEventListener("resize",resizeCanvas);for(let i=0;i<85;i++)particles.push({x:Math.random()*canvas.width,y:Math.random()*canvas.height,radius:Math.random()*2+1,speed:Math.random()*.4+.2});function animate(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle="rgba(255,255,255,.68)";particles.forEach(p=>{ctx.beginPath();ctx.arc(p.x,p.y,p.radius,0,Math.PI*2);ctx.fill();p.y-=p.speed;if(p.y<0){p.y=canvas.height;p.x=Math.random()*canvas.width}});requestAnimationFrame(animate)}animate()}
